[package]
name = "rustlearningrs"
version = "0.1.0"
authors = ["david-cattermole <cattermole91@gmail.com>"]
edition = "2018"

[lib]
name = "rustlearningrs"
crate_type = ["cdylib"]

[build-dependencies]
bindgen = "0.51.1"
cc = "1.0"

[dependencies]
libc = "0.2.0"
