[package]
name = "rustlearningrs"
version = "0.1.0"
authors = ["david-cattermole <cattermole91@gmail.com>"]
edition = "2018"

[lib]
name = "rustlearningrs"
crate_type = ["cdylib"]

[dependencies]
libc = "0.2.0"
